import type { TopLevelMenu } from "./menubar.types";

export const MENU_DATA: TopLevelMenu[] = [
  {
    id: "file",
    label: "File",
    items: [
      { id: "file-new", type: "action", label: "New File", shortcut: "Ctrl+N" },
      {
        id: "file-new-window",
        type: "action",
        label: "New Window",
        shortcut: "Ctrl+Shift+N",
        disabled: true,
      },
      { id: "file-sep-1", type: "separator" },
      {
        id: "file-open",
        type: "action",
        label: "Open File",
        shortcut: "Ctrl+O",
      },
      {
        id: "file-open-folder",
        type: "action",
        label: "Open Folder",
        shortcut: "Ctrl+K Ctrl+O",
      },
      { id: "file-sep-2", type: "separator" },
      { id: "file-save", type: "action", label: "Save", shortcut: "Ctrl+S" },
      {
        id: "file-save-as",
        type: "action",
        label: "Save As",
        shortcut: "Ctrl+Shift+S",
      },
      {
        id: "file-save-all",
        type: "action",
        label: "Save All",
        shortcut: "Ctrl+K S",
      },
      { id: "file-sep-3", type: "separator" },
      {
        id: "file-close",
        type: "action",
        label: "Close File",
        shortcut: "Ctrl+W",
      },
      { id: "file-sep-4", type: "separator" },
      { id: "file-exit", type: "action", label: "Exit" },
    ],
  },
  {
    id: "edit",
    label: "Edit",
    items: [
      { id: "edit-undo", type: "action", label: "Undo", shortcut: "Ctrl+Z" },
      { id: "edit-redo", type: "action", label: "Redo", shortcut: "Ctrl+Y" },
      { id: "edit-sep-1", type: "separator" },
      { id: "edit-cut", type: "action", label: "Cut", shortcut: "Ctrl+X" },
      { id: "edit-copy", type: "action", label: "Copy", shortcut: "Ctrl+C" },
      { id: "edit-paste", type: "action", label: "Paste", shortcut: "Ctrl+V" },
      { id: "edit-sep-2", type: "separator" },
      { id: "edit-find", type: "action", label: "Find", shortcut: "Ctrl+F" },
      {
        id: "edit-replace",
        type: "action",
        label: "Replace",
        shortcut: "Ctrl+H",
      },
      { id: "edit-sep-3", type: "separator" },
      {
        id: "edit-select-all",
        type: "action",
        label: "Select All",
        shortcut: "Ctrl+A",
      },
      {
        id: "edit-copy-line-down",
        type: "action",
        label: "Copy Line Down",
        shortcut: "Alt+Shift+Down",
      },
      {
        id: "edit-delete-line",
        type: "action",
        label: "Delete Line",
        shortcut: "Ctrl+Shift+K",
      },
      { id: "edit-sep-4", type: "separator" },
      {
        id: "edit-toggle-comment",
        type: "action",
        label: "Toggle Comment",
        shortcut: "Ctrl+/",
      },
    ],
  },
  {
    id: "view",
    label: "View",
    items: [
      {
        id: "view-command-palette",
        type: "action",
        label: "Command Palette",
        shortcut: "Ctrl+Shift+P",
      },
      { id: "view-sep-1", type: "separator" },
      {
        id: "view-explorer",
        type: "action",
        label: "Explorer",
        shortcut: "Ctrl+Shift+E",
        disabled: false,
      },
      {
        id: "view-terminal",
        type: "action",
        label: "Terminal",
        shortcut: "Ctrl+`",
        disabled: false,
      },
      { id: "view-sep-2", type: "separator" },
      {
        id: "view-zoom-in",
        type: "action",
        label: "Zoom In",
        shortcut: "Ctrl+=",
      },
      {
        id: "view-zoom-out",
        type: "action",
        label: "Zoom Out",
        shortcut: "Ctrl+-",
      },
      {
        id: "view-zoom-reset",
        type: "action",
        label: "Reset Zoom",
        shortcut: "Ctrl+0",
      },
      { id: "view-sep-3", type: "separator" },
      {
        id: "view-toggle-wordwrap",
        type: "action",
        label: "Toggle Word Wrap",
        shortcut: "Alt+Z",
      },
      { id: "view-toggle-minimap", type: "action", label: "Toggle Minimap" },
      {
        id: "view-toggle-breadcrumbs",
        type: "action",
        label: "Toggle Breadcrumbs",
        disabled: true,
      },
    ],
  },
  {
    id: "run",
    label: "Run",
    items: [
      {
        id: "run-code",
        type: "action",
        label: "Run Code",
        shortcut: "F5",
        disabled: true,
      },
      {
        id: "run-debug",
        type: "action",
        label: "Debug Code",
        shortcut: "F9",
        disabled: true,
      },
      { id: "run-sep-1", type: "separator" },
      {
        id: "run-step-forward",
        type: "action",
        label: "Step Forward",
        shortcut: "F10",
        disabled: true,
      },
      {
        id: "run-step-back",
        type: "action",
        label: "Step Back",
        shortcut: "F11",
        disabled: true,
      },
      {
        id: "run-stop",
        type: "action",
        label: "Stop",
        shortcut: "Shift+F5",
        disabled: true,
      },
      { id: "run-sep-2", type: "separator" },
      { id: "run-select-language", type: "action", label: "Select Language" },
      { id: "run-sep-3", type: "separator" },
      {
        id: "run-clear-output",
        type: "action",
        label: "Clear Output",
        disabled: true,
      },
    ],
  },
  {
    id: "language",
    label: "Language",
    items: [
      { id: "lang-python", type: "action", label: "Python" },
      { id: "lang-javascript", type: "action", label: "JavaScript" },
      { id: "lang-cpp", type: "action", label: "C++" },
      { id: "lang-c", type: "action", label: "C" },
      { id: "lang-java", type: "action", label: "Java" },
      { id: "lang-sep-1", type: "separator" },
      {
        id: "lang-more",
        type: "action",
        label: "(more coming soon)",
        disabled: true,
      },
    ],
  },
  {
    id: "help",
    label: "Help",
    items: [
      { id: "help-about", type: "action", label: "About AlgoLens" },
      { id: "help-sep-1", type: "separator" },
      {
        id: "help-docs",
        type: "action",
        label: "Documentation",
        disabled: true,
      },
      {
        id: "help-report",
        type: "action",
        label: "Report Issue",
        disabled: true,
      },
      { id: "help-sep-2", type: "separator" },
      {
        id: "help-shortcuts",
        type: "action",
        label: "Keyboard Shortcuts",
        shortcut: "Ctrl+K Ctrl+S",
      },
      { id: "help-sep-3", type: "separator" },
      {
        id: "help-benchmark",
        type: "action",
        label: "Run Classifier Benchmark (dev)",
      },
      { id: "help-performance", type: "action", label: "Performance Report" },
      { id: "help-export-study", type: "action", label: "Export Study Data" },
      { id: "help-sep-4", type: "separator" },
      {
        id: "help-updates",
        type: "action",
        label: "Check for Updates",
        disabled: true,
      },
    ],
  },
];
